### ISSUE TITLE
February 14th, 2022 Community Meeting

### ISSUE THREAD

**Issue by otaviof** [shipwright-io/community#58]
- Please add a topic in this thread and add a link to the GitHub issue associated with the topic.
- Please make sure you give folks enough time to review/discuss the topic offline on GitHub before coming into the meeting
- (optional) Paste the image of an animal 😸

**Comment by otaviof** [comment]
https://github.com/shipwright-io/image/issues/4 -- Centralized repository for all the API/CRD resources (/cc @ricardomaraschini)

![vulture's nest](https://live.staticflickr.com/65535/48848803057_a0972b38af_c_d.jpg)

**Comment by ricardomaraschini** [comment]
Image Abstraction Layer EP https://github.com/shipwright-io/community/pull/57

![capivara](https://user-images.githubusercontent.com/1385436/153850691-1b19e0f0-7f1d-45bb-b78b-2b64016be096.jpg)

**Comment by qu1queee** [comment]
- https://github.com/shipwright-io/community/discussions/60

**Comment by SaschaSchwarze0** [comment]
**Consolidate CRDs**
- Enrique: Tight relationship between CRDs and business logic
- Jason: Tekton and Knative have CRDs and code also co-located
- Sascha: we would have one more repo (build) which must get adopted after the API vs having at least one where one can do changes together
- Otavio: we would need to change the APIs first as this is usually most discussed; then later the implementation can adopt
- Enrique: why is OpenShift doing this -> Otavio: API stability, must not be broken
- Sascha: would be easier once our API is more stable
- Otavio: important is to review the API first -> Enrique: happens in the SHIP
- Conclusion:
  - We made the point that APIs need to be discussed in Ships
  - As of today, moving the APIs into an own project is considered over-complicating the process
  - At some point in the future when we are more stable, this can be considered again

**Image Abstraction Ship #27**
- Ricardo inviting everybody to read it: https://github.com/shipwright-io/community/pull/57
- PoC code available in https://github.com/shipwright-io/image/, any code in there can still change. Is just a special situation because the overall component is new.

**Owner rotation introduction by Enrique**
- Sascha: I like it, especially that we document what all needs to be looked at
- Otavio: how is Tekton doing this? -> Enrique giving details
- Jason: Tekton approach has same goal, but does not work perfectly because people are sometimes busy; not all owners / maintainers are doing it in Tekton
- Enrique: should be a best-can-do jobrole

**Enrique recommending https://github.com/shipwright-io/community/pull/53**
- Ricardo: seeing benefits of storing a tarball with the image proposal
- Jason: Tekton had similar scenarios but never came to it

**Matthias: playing around with OpenShift, what is the internal registry usually used for?**
- Ricardo: store image results of builds; cache images; disconnected environment where only the internal registry can go outside; oob references to common quay images
